definitions:
  types.Survey:
    properties:
      dataCriacao:
        type: string
      id:
        type: integer
      nome:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Health
  /survey:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.Survey'
            type: array
      tags:
      - Survey
  /test:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Test
swagger: "2.0"
